@startuml
object Usuario {
  nombre = "Manuel Masías"
}

object Rol {
  nombre = "Profesor"
}

object Permiso {
  nombre = "Colocar notas"
}

object BaseDeDatos {
  nombre = "Universidad Europea del Atlántico"
}

object Esquema {
  nombre = "Facultad de Ingeniería"
}

object Vista {
  nombre = "Ingeniería de Software I"
}

object Tabla {
  nombre = "Grupo 3er año"
}

object Indice {
  nombre = "Alejandro Juárez"
}

object Campo {
  nombre = "Examen Final"
  tipo = "Teórico"
}

object Constraint {
  descripcion = "Comprensión de conceptos"
}

object Key {
  valor = "9.0"
  escala = "0-10"
}

object Tipo {
  nombre = "Examen"
}

Usuario -- Rol
BaseDeDatos -right- Esquema
Rol -- Permiso
Esquema -- Vista
Permiso -- Vista
Vista -- Tabla
Tabla -- Indice
Indice -right- Campo
Tabla -- Campo
Campo -right- Constraint
Campo -- Key
Campo -- Tipo

hide empty members
@enduml
